In [3]:
import numpy as np
sr =np.array([1,2,3,4])
sr

array([1, 2, 3, 4])

In [18]:
import numpy as np
random_nos = [1,5,8,4,6,7,9]
sr = np.array(serial_nos)
random_nos

[1, 5, 8, 4, 6, 7, 9]

In [5]:
import numpy as np
a = np.zeros((4,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
import numpy as np

b= np.ones((3,8))
b

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
array_of_ones_int= np.ones((3,4)),dtype =np.int(16)
array_of_ones

SyntaxError: can't assign to function call (<ipython-input-17-c10720ff3ad5>, line 1)

In [21]:
import numpy as np

array_of_zeros_int = np.ones((3,4)),dtype = np.int(16)

array_of_zeros_int

SyntaxError: can't assign to function call (<ipython-input-21-c018ccf1783e>, line 3)

In [22]:
null = np.empty((5,8))
null

array([[9.45847692e-312, 9.45792547e-312, 2.84327065e-308,
        1.33360298e+241, 1.38222562e-309, 2.71115985e-181,
        8.58247829e-313, 6.52094399e-308],
       [1.33360422e+241, 6.21744767e-311, 1.96859884e-268,
        5.29978149e+180, 3.88171088e-307, 1.33360329e+241,
        4.47868432e-310, 3.06836125e+257],
       [8.73990021e+245, 7.83033561e-294, 1.27612992e-303,
        1.09385327e-303, 1.27630793e-303, 1.64088072e-303,
        5.48094824e-294, 3.81860922e-029],
       [5.76402061e-188, 7.16866764e-299, 1.09385187e-303,
        2.44135603e-260, 1.28022407e-303, 6.37144929e+202,
        1.46655526e-043, 2.58257726e-048],
       [2.01470488e-178, 1.59191579e-149, 9.68474856e+120,
        1.34656545e-043, 8.04888021e-169, 7.84566306e-294,
        4.28260870e+286, 8.59254119e-309]])

In [23]:
diagnol = np.eye(8)
diagnol

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
evens = np.arange(2,40,2)

evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [36]:
import numpy as np

intervals = np.arange(8,20,2.3)
                       
intervals

array([ 8. , 10.3, 12.6, 14.9, 17.2, 19.5])

In [37]:
twoood = np.array([(1,5,6,7,6,9),(2,8,7,6,9,6)])

twoood

array([[1, 5, 6, 7, 6, 9],
       [2, 8, 7, 6, 9, 6]])

In [38]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#reshaping

In [39]:
sr = np.arange(20).reshape(4,5)

sr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])