In [1]:
import numpy as np
array_one=np.array([4,1,5,7,8])
array_one

array([4, 1, 5, 7, 8])

In [2]:
numbers=[1,4558,145,45,78,15]

In [3]:
array_two=np.array(numbers)
array_two

array([   1, 4558,  145,   45,   78,   15])

In [4]:
array_of_zeros= np.zeros([8,4])
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])