In [1]:
import numpy as np

a = np.array([76,85,92,100])

b = np.array([45,80,76,10])


a+b

array([121, 165, 168, 110])

In [2]:
a-b

array([31,  5, 16, 90])

In [3]:
a/b

array([ 1.68888889,  1.0625    ,  1.21052632, 10.        ])

In [4]:
a%7

array([6, 1, 1, 2], dtype=int32)

In [5]:
#dot function

In [6]:
a = np.array([[4,7],[7,12]])

b = np.array([[8,16],[4,85]])

In [7]:
print('a:\n',a)

print('b:\n',b)

a:
 [[ 4  7]
 [ 7 12]]
b:
 [[ 8 16]
 [ 4 85]]


In [8]:
a*b

array([[  32,  112],
       [  28, 1020]])

In [9]:
a.dot(b)

array([[  60,  659],
       [ 104, 1132]])

In [10]:
b.dot(a)

array([[ 144,  248],
       [ 611, 1048]])

In [11]:
#unary oeprators

In [12]:
numbers = np.array([45,48,76,48,36,12100,78465,151])

In [13]:
numbers.sum()

90969

In [14]:
numbers.max()

78465

In [15]:
numbers.min()

36

In [16]:
numbers = np.arange(70).reshape(10,7)

In [17]:
numbers

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69]])

In [18]:
numbers.sum(axis=0)

array([315, 325, 335, 345, 355, 365, 375])

In [19]:
numbers.sum(axis=1)

array([ 21,  70, 119, 168, 217, 266, 315, 364, 413, 462])

In [20]:
numbers.max(axis=1)

array([ 6, 13, 20, 27, 34, 41, 48, 55, 62, 69])

In [21]:
numbers.mean(axis=0)

array([31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5])

In [23]:
numbers.var(axis=1)

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [24]:
#universal funcions of numpy

In [25]:
price_details = np.array([700,845,960,975,460,320,470,380,468,720,490,820])

In [26]:
print('total gross price of the products:')

print(np.mean(price_details))

total gross price of the products:
634.0


In [28]:
print(np.median(price_details))

595.0
