In [1]:
import numpy as np

salaries =np.genfromtxt('salary.csv',delimiter = ',')

In [2]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [3]:
salaries.shape

(1147,)

In [4]:
mean =np.mean(salaries)

In [5]:
mean

55894.53879686138

In [6]:
median=np.median(salaries)

In [7]:
median

48000.0

In [14]:
mean =np.mean(salaries)
median =np.median(salaries)
sd =np.std(salaries)
variance =np.var(salaries)

In [15]:
print('mean =%i'%mean)

print('median =%i'%median)

print('standard deviation =%i'%sd)

print('variance =%i'%variance)

mean =55894
median =48000
standard deviation =55170
variance =3043770333


In [16]:
#indexing and slicing of the arrays

In [17]:
a =np.arange(17)**3

In [18]:
a

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096], dtype=int32)

In [19]:
a[-4]

2197

In [20]:
a[4]

64

In [21]:
a[9]

729

In [22]:
a[4:8]

array([ 64, 125, 216, 343], dtype=int32)

In [24]:
a[3:10]

array([ 27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [27]:
students =np.array([['mani','sai','shyam','karim','sairaj'],
                   [75,100,70,65,62],
                   [80,100,89,90,97]])

In [28]:
students[0]

array(['mani', 'sai', 'shyam', 'karim', 'sairaj'], dtype='<U6')

In [29]:
students[2]

array(['80', '100', '89', '90', '97'], dtype='<U6')

In [30]:
print(students)

[['mani' 'sai' 'shyam' 'karim' 'sairaj']
 ['75' '100' '70' '65' '62']
 ['80' '100' '89' '90' '97']]


In [31]:
students[0,1]

'sai'